### PR TITLE
Fixed non-owner users receiving error when combatant exits combat

### LINKED ISSUE #2214: Player token update throws error
When in combat, it looks like code in player context (i.e. run on the client of the player) tries to update other tokens and runs into an error.

Steps to reproduce:
	- Create new Game World
	- Create additional user: Player_1
	- Create actor PC1 (and give Player_1 ownership)
	- Create actor NPC1 as enemy
	- Create new scene
	- Put both tokens on scene
	- Toggle combat state of token NPC1(!) (add it to combat tracker)
	- Toggle combat state of token NPC1 (remove it from combat tracker)

The following error is thrown on the player's client:
	

gurps.js:2832 Combatant removed: NPC1 - resetting token actions
foundry.js:72076 User Player_1 lacks permission to update Token [6Pf9l0zdgBn4g0aW] in parent Scene [ZvrKQCmZDtWUIcdV]
fetch @ foundry.js:72076Understand this error
gurps.js:2834 Uncaught (in promise) Error: User Player_1 lacks permission to update Token [6Pf9l0zdgBn4g0aW] in parent Scene [ZvrKQCmZDtWUIcdV]
    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5101
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ServerDatabaseBackend._updateDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4748)
    at async Semaphore._try (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)

Scene.ZvrKQCmZDtWUIcdV.Token.6Pf9l0zdgBn4g0aW.Actor.HGafHrsBB0qsoxwe

Additional Information:
The document UUI of the NPC 1 token in the scene is Scene.ZvrKQCmZDtWUIcdV.Token.6Pf9l0zdgBn4g0aW.Actor.HGafHrsBB0qsoxwe

### LINKED ISSUE #2246: v13: Select Manuever via Token HUD is not working

### PR DESCRIPTION
**Pull request by rinickolous**
I changed the functions responsible from being called via hooks to simply extending the combatant's own _preDelete and _onCreate side effect functions. I don't think we should be using hooks for this sort of functionality, that's more appropriate for modules. In any case, using _preDelete and _onCreate exposes the user and userId elements which are required for this fix.

Not strictly related I suppose but I noticed an issue with the TokenHUD app while working on this which was related to the app moving from JQuery to unwrapped HTML. I converted the associated functionality to match, so that fix is included with this PR too. I can move it and submit it separately, but since it's at least somewhat related to this I thought I'd bundle it in.

This resolves #2214 .
This also resolves #2246 , provided I understand that issue correctly.

### CODE REVIEW

File: module/gurps.js [hunk 1]
```diff
@@ -1927,6 +1929,8 @@ if (!globalThis.GURPS) {
     // @ts-ignore
     CONFIG.Actor.documentClass = GurpsActor
     CONFIG.Item.documentClass = GurpsItem
+    CONFIG.Combat.documentClass = CombatGURPS
+    CONFIG.Combatant.documentClass = CombatantGURPS
```
Comment (mjeffw) [inline module/gurps.js]: If `combat` was a module, this could be moved into the `init` method.

File: module/gurps.js [hunk 2]
```diff
@@ -2514,15 +2518,15 @@ if (!globalThis.GURPS) {
...
+    // })
 
-    Hooks.on('deleteCombatant', async (combatant, combat) => {
-      console.log(`Combatant removed: ${combatant.token.name} - resetting token actions`)
-      await resetTokenActionsForCombatant(combatant)
-    })
+    // Hooks.on('deleteCombatant', async (combatant, combat) => {
+    //   console.log(`Combatant removed: ${combatant.token.name} - resetting token actions`)
+    //   await resetTokenActionsForCombatant(combatant)
+    // })
```
Comment (mjeffw) [inline module/gurps.js]: Make sure we go back and delete this code after we feel confident the new changes worked.

**Review by mjeffw — CHANGES_REQUESTED** [review]

File: module/gurps.js (hunk 1 above)
Comment (rinickolous) [reply module/gurps.js]: moved to its own module

File: module/gurps.js [hunk 3]
```diff
@@ -2514,16 +2517,6 @@ if (!globalThis.GURPS) {
       await handleCombatTurn(combat, turn)
     })
 
-    Hooks.on('deleteCombat', async combat => {
```
Comment (mjeffw) [inline module/gurps.js:2519]: I'm happy to see more and more low level stuff being pulled out of the catch-all `gurps.js` file and moved to a submodule. Thanks.

**Review by mjeffw — APPROVED** [review]
