### PR TITLE
Fixed aim bonus not resetting after being used once in combat.

### LINKED ISSUE #2153: ACC bonus for Aim only works once per combat
Using Tagged modifiers with auto-apply and roll confirmation, the first Aim-attack sequence in a given combat adds weapon ACC, but the second and any subsequent Aim-attack sequences, no matter how far apart they happen in the same combat, only adds +1 as if it were an extra turn of Aim.

Ending combat and then starting it again allows ACC Aim bonus to work again, but only on the first Aim-attack sequence.

May be related to #2152 

First Aim-attack sequences in combat:

Image

All subsequent Aim-attack sequences

Image

### PR DESCRIPTION
**Pull request by rinickolous**
The issue was caused by explicitly assigning `undefined` as a value rather than using `null`. There are a few other instances of this happening in the GGA code with as yet unknown consequences, so I would strongly recommend not doing so in the future.

This resolves #2153 .

### CODE REVIEW

File: module/token-actions.js [hunk 1]
```diff
@@ -90,9 +90,9 @@ export class TokenActions {
     this.extraActions = 0
     this.rapidStrikeBonus = 0
 
-    this.canDefend = undefined
-    this.canAttack = undefined
-    this.canMove = undefined
+    this.canDefend = null
+    this.canAttack = null
+    this.canMove = null
```
Comment (mjeffw) [inline module/token-actions.js:95]: Is there a preference to using `null` as opposed to `undefined`?
