### PR TITLE
Bugfix: Movement range color indicators do not appear on gridless maps

### LINKED ISSUE #2489: The color indicator for movement does not work in gridless maps
Movement is shown as green for normal movement, yellow for sprint, then red for over max movement in grid maps for token movement. This feature does not seem to be working for gridless maps
It just show a single colored line that is purple

I had this working with v12 and Drag Ruler module.

### PR DESCRIPTION
**Pull request by rinickolous**
The implementation _with_ grids highlights each traversed grid, but this is impossible for gridless maps.
Overrode the function which determines the color of the segment line itself, and made this change color for
gridless maps instead.

Fixes #2489

### CODE REVIEW

File: module/token/token-ruler.ts [hunk 1]
```diff
@@ -8,38 +8,65 @@ function registerTokenRuler() {
...
-      const yards = Length.from(waypoint.measurement.cost, units as LengthUnit)?.to(Length.Unit.Yard).value ?? 0
+      const yards = Length.from(distance, units as LengthUnit)?.to(Length.Unit.Yard).value ?? 0
 
       if (yards === 0) {
-        return data
+        return defaultColor
         // @ts-expect-error: waiting for actor update to DataModel
       } else if (yards <= Math.ceil(actor.system.currentmove / 10)) {
-        return { ...data, color: 0x0000ff } // Step: blue
+        return 0x0000ff // Step: blue
```
Comment (mjeffw) [inline module/token/token-ruler.ts]: Let's turn these colors into constants declared in `module/token/constants.ts`.

**Comment by rinickolous** [comment]
@mjeffw donezo

**Review by mjeffw — APPROVED** [review]
