### PR TITLE
fix: update quotedAttackName function to handle quotes and add tests

### LINKED ISSUE #2461: Dashes in Ranged Weapon names used as Modifiers
If you have a ranged weapon with a - and number in the name, it's treated as a modifier. Not sure if this is intentional.

I encountered this by having a gun named AK-98. Clicking to roll the skill level caused it to have a -98 modifier on the roll (It took me awhile to realize why).

Image

Image

### PR DESCRIPTION
**Pull request by mjeffw**
Fixes #2461

### CODE REVIEW

File: lib/utilities.js [hunk 1]
```diff
@@ -574,13 +574,17 @@ export function arrayBuffertoBase64(buffer) {
...
+ */
 export function quotedAttackName(item) {
-  let q = '"'
-  let n = item.name
-  if (n.includes(q)) q = "'"
-  if (!!item.mode) n = n + ' (' + item.mode + ')'
-  if (n.includes(' ')) n = q + n + q
-  return n
+  const quoteCharacter = item.name.includes(DOUBLE_QUOTE) ? SINGLE_QUOTE : DOUBLE_QUOTE
+  let n = !!item.mode ? item.name + ' (' + item.mode + ')' : item.name
```
Comment (daynin) [inline lib/utilities.js]: I'd suggest avoiding short names like `n`

File: lib/utilities.js [hunk 2]
```diff
@@ -574,13 +574,17 @@ export function arrayBuffertoBase64(buffer) {
...
+ * @returns {string}
+ */
 export function quotedAttackName(item) {
-  let q = '"'
-  let n = item.name
-  if (n.includes(q)) q = "'"
-  if (!!item.mode) n = n + ' (' + item.mode + ')'
-  if (n.includes(' ')) n = q + n + q
-  return n
+  const quoteCharacter = item.name.includes(DOUBLE_QUOTE) ? SINGLE_QUOTE : DOUBLE_QUOTE
```
Comment (daynin) [inline lib/utilities.js]: Probably it's still can fail if a skill contains both quote types - `Someone's "Super Power"`? I'd suggest using "`" character or even square brackets. I think we should reconsider some syntax to avoid issues like that

File: lib/utilities.js [hunk 3]
```diff
@@ -574,13 +574,17 @@ export function arrayBuffertoBase64(buffer) {
...
+  let n = !!item.mode ? item.name + ' (' + item.mode + ')' : item.name
+  return quoteCharacter + n + quoteCharacter
```
[the remark this answers is not in the document]
Comment (daynin) [reply lib/utilities.js]: Just noticed that copilot suggested the same about both types of quotes

File: test/utilities.test.ts [hunk 4]
```diff
@@ -284,6 +284,16 @@ describe('utilities', () => {
       const item = { name: 'Attack', mode: 'Mode' }
       expect(utilities.quotedAttackName(item)).toBe('"Attack (Mode)"')
     })
+
+    test('should return quoted attack name without mode', () => {
```
Comment (daynin) [inline test/utilities.test.ts:288]: I think we should add a test that reproduced exact bug from the issue.I'll be easier to find relation between the change and the issue later

File: lib/utilities.js (hunk 2 above)
Comment (mjeffw) [reply lib/utilities.js]: We need to overhaul OTFs in the near future. I don't want to go to another delimiter until we do, as the change will ripple throughout the code.

File: test/utilities.test.ts (hunk 4 above)
Comment (mjeffw) [reply test/utilities.test.ts:288]: done

**Comment by mjeffw** [comment]
> @mjeffw is this ready for re-review?

Yes

**Comment by rinickolous** [comment]
@mjeffw do make sure to add the bugfix to the change log before merging
