### PR TITLE
Fixed various v13 sidebar issues

### LINKED ISSUE #2249: v13 Missing "Mass Import" button on Actors tab

### LINKED ISSUE #2255: v13 Missing "Import Equipment Library" button on compendium tab

### LINKED ISSUE #2256: V13 OTF formulae dragged to chat are not sent as messages

### PR DESCRIPTION
**Pull request by rinickolous**
- Fixed "Multiple Import" button not appearing on Actor tab in sidebar.
- Fixed "Import Equipment Library" button not appearing in Compendium tab in sidebar.
- Fixed OTF formulae dragged to the sidebar not posting chat messages.

Note: This branch is currently based on the general v12 compatibility branch in my other PR (#2253). It needs that PR to be merged for this one to be compatible with v12 at all.

Resolves #2249 
Resolves #2255 
Resolves #2256

### CODE REVIEW

File: module/item-import.js [hunk 1]
```diff
@@ -36,14 +32,25 @@ export const AddImportEquipmentButton = async function (html) {
         {
           action: 'cancel',
           label: game.i18n.localize('GURPS.cancel'),
```
Comment (mjeffw) [inline module/item-import.js:34]: Just FYI -- DialogV2 will automatically localize button labels.
```suggestion
          label: 'GURPS.cancel',
```
